language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system

before_install:
  - BASEDIR=$(pwd)
  - echo BASEDIR $BASEDIR
  - mkdir -p ~/.aws
  - echo '[default]' >~/.aws/credentials
  - echo 'aws_secret_key = ${AWS_SECRET_KEY}'>>~/.aws/credentials
  - echo 'aws_access_key_id = ${AWS_ACCESS_KEY_ID}'>>~/.aws/credentials
  - cat ~/.aws/credentials
  - pip install --user awscli
  - aws ls s3://hughperkinstravis
script:
  - ls
notifications:
  email:
    on_success: never
    on_failure: never
