language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: xcode7.3
      rvm: system

before_install:
  - BASEDIR=$(pwd)
  - echo BASEDIR $BASEDIR
  - time tar -czf /tmp/foo.tar.gz /usr/local/bin
  - time tar -cjf /tmp/foo.tar.bz2 /usr/local/bin
  - ls -lh /tmp/foo.tar.gz
  - pigz
script:
  - ls
notifications:
  email:
    on_success: never
    on_failure: never

