language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: xcode7.3
      rvm: system

before_install:
  - BASEDIR=$(pwd)
  - echo BASEDIR $BASEDIR
  - pip install --user awscli
  - echo hello > /tmp/foo
  - ~/Library/Python/2.7/bin/aws s3 cp --quiet /tmp/foo s3://hughperkinstravis/tmp/test.foo

script:
  - whoami
notifications:
  email:
    on_success: never
    on_failure: never
