language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: xcode7.3
      rvm: system

before_install:
  - BASEDIR=$(pwd)
  - echo BASEDIR $BASEDIR
  - pip install --user awscli
  - bash travis/install-python.sh
  - bash travis/build-swig.sh
  - bash swig_build.sh

script:
  - whoami
notifications:
  email:
    on_success: never
    on_failure: never
