language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system

before_install:
  - BASEDIR=$(pwd)
  - echo BASEDIR $BASEDIR
  - mkdir -p ~/.aws
  - echo '[default]' >~/.aws/credentials
  - echo "aws_secret_key = ${AWS_SECRET_KEY}">>~/.aws/credentials
  - echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}">>~/.aws/credentials
  - pip install --user awscli
  - ~/Library/Python/2.7/bin/aws s3 ls s3://hughperkinstravis
  - echo =============== bazel =====================
  - cd ${BASEDIR}/soft
  - java -version
  - wget https://github.com/bazelbuild/bazel/releases/download/0.3.2/bazel-0.3.2-installer-darwin-x86_64.sh
  - chmod +x bazel-0.3.2-installer-darwin-x86_64.sh
  - ./bazel-0.3.2-installer-darwin-x86_64.sh --user
  - export PATH=$HOME/bin:$PATH
  - bazel version
  - which bazel
  - echo ======== bazel test ===============
  - cd ${BASEDIR}
  - bazel build //...
  - ls -lh
  - ls -lh ~/.cache
  - ls -lh ~/.cache/bazel
  - cd ~/.cache/bazel
  - tar -cjf bazel.tar.bz2 *
  - ls -lh
  - ~/Library/Python/2.7/bin/aws s3 cp bazel.tar.bz2 s3://hughperkinstravis/cache/test-bazel.tar.bz2
script:
  - ls
notifications:
  email:
    on_success: never
    on_failure: never
