language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: xcode7.3
      rvm: system

before_install:
  - BASEDIR=$(pwd)
  - echo BASEDIR $BASEDIR
  - /bin/sleep 20 &
  - echo after sleep
  - ps -ef | grep sleep
  - ps -ef | grep sleep | grep -v grep | awk '{print $2}' | xargs -L1 kill 
  - after ps
  - ps -ef | grep sleep
script:
  - whoami
notifications:
  email:
    on_success: never
    on_failure: never
