language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: xcode7.3
      rvm: system

before_install:
  - BASEDIR=$(pwd)
  - echo BASEDIR $BASEDIR
  - export TIME=%e
  - time sleep 1.6
  - /usr/bin/time sleep 1.9
  - res = $(/usr/bin/time sleep 1.9)
  - echo res ${res}
  - if [ $(echo "$res < 2.3" | bc -l) ]; then { echo yes; } else { echo no; } fi
  - if [ $(echo "$res < 1.7" | bc -l) ]; then { echo yes; } else { echo no; } fi
script:
  - ls
notifications:
  email:
    on_success: never
    on_failure: never

