language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: xcode7.3
      rvm: system

before_install:
  - BASEDIR=$(pwd)
  - echo BASEDIR $BASEDIR
  - start=`python ${BASEDIR}/travis/seconds.py`
  - sleep 4
  - end=`python ${BASEDIR}/travis/seconds.py`
  - echo start $start end $end
  - echo diff `echo "$end - $start" | bc -l`
  - echo diff: $(($end - $start))
  - if [ `echo "$end - $start > 3" | bc -l` -eq 1 ]; then { echo yes; } else { echo no; } fi
  - if [ `echo "$end - $start > 5" | bc -l` -eq 1 ]; then { echo yes; } else { echo no; } fi
  - time tar -czf /tmp/foo.tar.gz /usr/local/bin
  - ls -lh /tmp/foo.tar.gz
  - pigz
script:
  - ls
notifications:
  email:
    on_success: never
    on_failure: never

