language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system

before_install:
  - BASEDIR=$(pwd)
  - echo BASEDIR $BASEDIR
  - echo TRAVIS_BRANCH $TRAVIS_BRANCH
  - pip install --user awscli
  - bash ${BASEDIR}/travis/download.sh
  - echo =============== bazel =====================
  - mkdir -p ${BASEDIR}/soft
  - cd ${BASEDIR}/soft
  - java -version
  - wget https://github.com/bazelbuild/bazel/releases/download/0.3.2/bazel-0.3.2-installer-darwin-x86_64.sh
  - chmod +x bazel-0.3.2-installer-darwin-x86_64.sh
  - ./bazel-0.3.2-installer-darwin-x86_64.sh --user
  - export PATH=$HOME/bin:$PATH
  - bazel version
  - which bazel
  - time bazel build //...
  - echo ======== bazel test ===============
  - cd ${BASEDIR}
  - bash ${BASEDIR}/travis/upload.sh
script:
  - ls
notifications:
  email:
    on_success: never
    on_failure: never
