language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system

before_install:
  - BASEDIR=$(pwd)
  - echo BASEDIR $BASEDIR
  - echo TRAVIS_BRANCH $TRAVIS_BRANCH
  - pip install --user awscli
  - bash ${BASEDIR}/travis/download.sh bazelcache /private/var/tmp/_bazel_travis
  - bash ${BASEDIR}/travis/download.sh cocl ${BASEDIR}/cuda-on-cl
  - echo ============ clang ============
  - mkdir -p ${BASEDIR}/soft
  - cd ${BASEDIR}/soft
  - CLANG_VERSION=3.8.0
  - wget http://llvm.org/releases/${CLANG_VERSION}/clang+llvm-${CLANG_VERSION}-x86_64-apple-darwin.tar.xz
  - tar -xf clang+llvm-${CLANG_VERSION}-x86_64-apple-darwin.tar.xz
  - ls
  - export CLANG_HOME=${PWD}/clang+llvm-${CLANG_VERSION}-x86_64-apple-darwin
  - echo ======= cuda-on-cl ==================
  - cd ${BASEDIR}
  - if [[ ! -d cuda-on-cl ]]; then { git clone --recursive https://github.com/hughperkins/cuda-on-cl; } fi
  - cd cuda-on-cl
  - mkdir -p build
  - cd build
  - time cmake .. -DBUILD_TESTS=ON -DCLANG_HOME=${CLANG_HOME}
  - time make -j 4
  - sudo make install
  - bash ${BASEDIR}/travis/upload.sh cocl ${BASEDIR}/cuda-on-cl
  - echo =============== bazel =====================
  - mkdir -p ${BASEDIR}/soft
  - cd ${BASEDIR}/soft
  - java -version
  - wget https://github.com/bazelbuild/bazel/releases/download/0.3.2/bazel-0.3.2-installer-darwin-x86_64.sh
  - chmod +x bazel-0.3.2-installer-darwin-x86_64.sh
  - ./bazel-0.3.2-installer-darwin-x86_64.sh --user
  - export PATH=$HOME/bin:$PATH
  - bazel version
  - which bazel
  - echo ======== bazel test ===============
  - cd ${BASEDIR}
  - time bazel --batch build //...
  - bash ${BASEDIR}/travis/upload.sh bazelcache /private/var/tmp/_bazel_travis
script:
  - ls
notifications:
  email:
    on_success: never
    on_failure: never
