language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: xcode7.3
      rvm: system

script:
- wget http://deepcl.hughperkins.com/Downloads/boost-1.61.0.tar.bz2
- mkdir boost
- mkdir boost/boost
- cd boost/boost
- tar -xf ../../boost-1.61.0.tar.bz2
- ls
- cd ../..
- ls
- clang -framework OpenCL -g -I/usr/include -std=c++11 -Iboost -o test1 test1.cpp
- ./test1
