language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system

before_install:
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - BASEDIR=$(pwd)
  - echo BASEDIR ${BASEDIR}
  - mkdir soft
  - cd soft
  - CLANG_VERSION=3.8.0
  - wget http://llvm.org/releases/${CLANG_VERSION}/clang+llvm-${CLANG_VERSION}-x86_64-apple-darwin.tar.xz
  - tar -xf clang+llvm-${CLANG_VERSION}-x86_64-apple-darwin.tar.xz
  - export CLANG_HOME=${PWD}/clang+llvm-${CLANG_VERSION}-x86_64-apple-darwin

script:
  - cd ${BASEDIR}
  - mkdir build
  - cd build
  - echo CLANG_HOME ${CLANG_HOME}
  - cmake .. -DCLANG_HOME=${CLANG_HOME}
  - make -j 8
  - ./test_llvm_valuemap

notifications:
  email:
    on_success: change
    on_failure: always
