language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: xcode7.3
      rvm: system

before_install:
  - BASEDIR=$(pwd)
  - echo BASEDIR $BASEDIR

  - python test_platform.py
  - bash ${BASEDIR}/travis/install-python.sh
  - python3 test_platform.py

script:
  - whoami
notifications:
  email:
    on_success: never
    on_failure: never
